version: "3.7"
services:
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${ROOT_FOLDER_HOST}/media/data/calibre:/calibre
      - ${ROOT_FOLDER_HOST}/media/data/books:/books
    ports:
      - ${APP_PORT}:8083
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.calibre-web-automated-web-redirect.redirectscheme.scheme: https
      traefik.http.services.calibre-web-automated.loadbalancer.server.port: 8083
      # Web
      traefik.http.routers.calibre-web-automated-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.calibre-web-automated-insecure.entrypoints: web
      traefik.http.routers.calibre-web-automated-insecure.service: calibre-web-automated
      traefik.http.routers.calibre-web-automated-insecure.middlewares: calibre-web-automated-web-redirect
      # Websecure
      traefik.http.routers.calibre-web-automated.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.calibre-web-automated.entrypoints: websecure
      traefik.http.routers.calibre-web-automated.service: calibre-web-automated
      traefik.http.routers.calibre-web-automated.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.calibre-web-automated-local-insecure.rule: Host(`calibre-web-automated.${LOCAL_DOMAIN}`)
      traefik.http.routers.calibre-web-automated-local-insecure.entrypoints: web
      traefik.http.routers.calibre-web-automated-local-insecure.service: calibre-web-automated
      traefik.http.routers.calibre-web-automated-local-insecure.middlewares: calibre-web-automated-web-redirect
      # Local domain secure
      traefik.http.routers.calibre-web-automated-local.rule: Host(`calibre-web-automated.${LOCAL_DOMAIN}`)
      traefik.http.routers.calibre-web-automated-local.entrypoints: websecure
      traefik.http.routers.calibre-web-automated-local.service: calibre-web-automated
      traefik.http.routers.calibre-web-automated-local.tls: true
      runtipi.managed: true
